development:
  adapter: mysql
  database: demo_app
  host: 127.0.0.1
  username: root
  password:

test:
  adapter: mysql
  database: demo_app
  host: 127.0.0.1
  username: root
  password:

production:
  adapter: mysql
  database: demo_app
  host: 127.0.0.1
  username: root
  password:
